// <auto-generated />
namespace WebAPI_BookEF.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-61023")]
    public sealed partial class addModel : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(addModel));
        
        string IMigrationMetadata.Id
        {
            get { return "201712130151304_addModel"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
